CREATE TABLE USER ( LOGIN TEXT NOT NULL,
					MDP TEXT NOT NULL,
					CATEGORIE_USER INTEGER NOT NULL,
					NOM_USER TEXT NOT NULL,
					LANGUE TEXT NOT NULL,
					EMAIL TEXT NOT NULL,
					SEX TEXT NOT NULL,
					GSM INTEGER,
					ADRESSE TEXT,
					PRIMARY KEY (LOGIN),
					UNIQUE(EMAIL)
					);

CREATE TABLE RATING ( LOGIN TEXT NOT NULL REFERENCES USER,
					  ID_PRODUIT INTEGER NOT NULL,
					  NOTE REAL NOT NULL
					);

CREATE TABLE STRING (ID_STRING INTEGER NOT NULL,
						LANGUE TEXT NOT NULL,
						TEXTE TEXT NOT NULL
					);

CREATE TABLE PRODUIT (  ID_PROD INTEGER NOT NULL,
						DESCR INTEGER NOT NULL REFERENCES STRING,
						NOM_PRODUIT INTEGER NOT NULL REFERENCES STRING UNIQUE,
						CATEGORY INTEGER NOT NULL REFERENCES STRING,
						IMAGE BLOB,
						PRIX REAL NOT NULL,
						SEUIL INTEGER NOT NULL,
						PRIMARY KEY (ID_PROD)
					);

CREATE TABLE LOT ( ID_LOT INTEGER NOT NULL,
					IDPROD INTEGER NOT NULL REFERENCES PRODUIT,
					DATELOT TEXT NOT NULL,
					QTY INTEGER NOT NULL,
					PRIMARY KEY (ID_LOT)
				 );

CREATE TABLE QUANTITY ( ID_PROD INTEGER NOT NULL REFERENCES PRODUIT,
						ID_COMMAND INTEGER NOT NULL REFERENCES COMMAND,
						QUANTITY INTEGER NOT NULL
						);

CREATE TABLE COMMAND ( ID_COMMAND INTEGER NOT NULL,
						LOGIN TEXT NOT NULL REFERENCES USER,
						STATE INTEGER NOT NULL,
						DATE_COMMAND TEXT NOT NULL,
						TABL INTEGER NOT NULL,
						PRIMARY KEY (ID_COMMAND)
						);
