-- Calcul du RATING d'un produit
SELECT SUM(NOTE)/COUNT(NOTE) as Rating 
FROM RATING 
WHERE ID_PRODUIT = 1

-- Calcul des factures des commandes non payées (state = 1) par table
SELECT COMMAND.ID_COMMAND as NumCommande, COMMAND.TABL as TableCom, SUM(ROUND(PRODUIT.PRIX*QUANTITY.QUANTITY,2)) AS Total
FROM COMMAND, PRODUIT, QUANTITY
WHERE COMMAND.STATE != 0 AND PRODUIT.ID_PROD = QUANTITY.ID_PROD AND COMMAND.ID_COMMAND = QUANTITY.ID_COMMAND
GROUP BY COMMAND.ID_COMMAND -- On peut grouper par ID_COMMAND ou par TABL.





