-- Calcul du RATING d'un produit
SELECT SUM(NOTE)/COUNT(NOTE) as Rating 
FROM RATING 
WHERE ID_PRODUIT = 1

-- Calcul du RATING de tous les produits notés avec leur nom
SELECT STRING.TEXTE as Nom, SUM(RATING.NOTE)/COUNT(RATING.NOTE) as Rating 
FROM RATING, PRODUIT, STRING
WHERE PRODUIT.ID_PROD = RATING.ID_PRODUIT AND PRODUIT.NOM_PRODUIT = STRING.ID_STRING AND LANGUE = 'fr'
GROUP BY PRODUIT.ID_PROD

-- Calcul des factures des commandes non payées (state = 1) par table
SELECT COMMAND.ID_COMMAND as NumCommande, COMMAND.TABL as TableCom, SUM(ROUND(PRODUIT.PRIX*QUANTITY.QUANTITY,2)) AS Total
FROM COMMAND, PRODUIT, QUANTITY
WHERE COMMAND.STATE != 0 AND PRODUIT.ID_PROD = QUANTITY.ID_PROD AND COMMAND.ID_COMMAND = QUANTITY.ID_COMMAND
GROUP BY COMMAND.ID_COMMAND -- On peut grouper par ID_COMMAND ou par TABL.

-- Description d'un produit selon la langue de l'utilisateur
SELECT USER.LOGIN AS Nom, STRING.TEXTE AS Descrption
FROM USER, PRODUIT, STRING
WHERE USER.LANGUE = STRING.LANGUE AND PRODUIT.ID_PROD = 1 AND STRING.ID_STRING = PRODUIT.DESCR








